"""UR3 joint angle readout group."""

from PyQt5 import QtCore, QtGui, QtWidgets


class JointReadoutPanel:
    """UR3 joint angle readout group.

    Mixin contributing this panel's widgets to :class:`~radar_hgr.ui.layout.main_window.Ui_MainWindow`.
    """

    def build_joint_panel(self, MainWindow):
        """Instantiate and position this panel's widgets."""
        self.joint_position = QtWidgets.QGroupBox(self.tab2)
        self.joint_position.setGeometry(QtCore.QRect(1210, 405, 181, 310))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.joint_position.setFont(font)
        self.joint_position.setStyleSheet("background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.522727, radius:0.5, fx:0.507, fy:0.516636, stop:0.244318 rgba(255, 255, 255, 255), stop:0.715909 rgba(255, 255, 255, 255), stop:0.960227 rgba(184, 254, 255, 255));")
        self.joint_position.setObjectName("joint_position")

        self.degree_0 = QtWidgets.QLabel(self.joint_position)
        self.degree_0.setGeometry(QtCore.QRect(160, 30, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_0.setFont(font)
        self.degree_0.setObjectName("degree_0")

        self.shoulder = QtWidgets.QLabel(self.joint_position)
        self.shoulder.setGeometry(QtCore.QRect(90, 75, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.shoulder.setFont(font)
        self.shoulder.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulder.setStyleSheet("border : 2px solid blue")
        self.shoulder.setObjectName("shoulder")

        self.base = QtWidgets.QLabel(self.joint_position)
        self.base.setGeometry(QtCore.QRect(90, 30, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.base.setFont(font)
        self.base.setAlignment(QtCore.Qt.AlignCenter)
        self.base.setStyleSheet("border : 2px solid blue")
        self.base.setObjectName("base")

        self.elbow = QtWidgets.QLabel(self.joint_position)
        self.elbow.setGeometry(QtCore.QRect(90, 120, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.elbow.setFont(font)
        self.elbow.setAlignment(QtCore.Qt.AlignCenter)
        self.elbow.setStyleSheet("border : 2px solid blue")
        self.elbow.setObjectName("elbow")

        self.label_elbow = QtWidgets.QLabel(self.joint_position)
        self.label_elbow.setGeometry(QtCore.QRect(10, 120, 51, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_elbow.setFont(font)
        self.label_elbow.setObjectName("label_elbow")

        self.label_shoulder = QtWidgets.QLabel(self.joint_position)
        self.label_shoulder.setGeometry(QtCore.QRect(10, 75, 75, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_shoulder.setFont(font)
        self.label_shoulder.setObjectName("label_shoulder")

        self.label_base = QtWidgets.QLabel(self.joint_position)
        self.label_base.setGeometry(QtCore.QRect(10, 30, 41, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_base.setFont(font)
        self.label_base.setObjectName("label_base")

        self.wrist_1 = QtWidgets.QLabel(self.joint_position)
        self.wrist_1.setGeometry(QtCore.QRect(10, 170, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_1.setFont(font)
        self.wrist_1.setObjectName("wrist_1")

        self.wrist_2 = QtWidgets.QLabel(self.joint_position)
        self.wrist_2.setGeometry(QtCore.QRect(10, 215, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_2.setFont(font)
        self.wrist_2.setObjectName("wrist_2")

        self.wrist_3 = QtWidgets.QLabel(self.joint_position)
        self.wrist_3.setGeometry(QtCore.QRect(10, 260, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_3.setFont(font)
        self.wrist_3.setObjectName("wrist_3")

        self.wrist_4 = QtWidgets.QLabel(self.joint_position)
        self.wrist_4.setGeometry(QtCore.QRect(90, 170, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_4.setFont(font)
        self.wrist_4.setAlignment(QtCore.Qt.AlignCenter)
        self.wrist_4.setStyleSheet("border : 2px solid blue")
        self.wrist_4.setObjectName("wrist_4")

        self.wrist_5 = QtWidgets.QLabel(self.joint_position)
        self.wrist_5.setGeometry(QtCore.QRect(90, 215, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_5.setFont(font)
        self.wrist_5.setAlignment(QtCore.Qt.AlignCenter)
        self.wrist_5.setStyleSheet("border : 2px solid blue")
        self.wrist_5.setObjectName("wrist_5")

        self.wrist_6 = QtWidgets.QLabel(self.joint_position)
        self.wrist_6.setGeometry(QtCore.QRect(90, 260, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_6.setFont(font)
        self.wrist_6.setAlignment(QtCore.Qt.AlignCenter)
        self.wrist_6.setStyleSheet("border : 2px solid blue")
        self.wrist_6.setObjectName("wrist_6")

        self.degree_1 = QtWidgets.QLabel(self.joint_position)
        self.degree_1.setGeometry(QtCore.QRect(160, 75, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_1.setFont(font)
        self.degree_1.setObjectName("degree_1")

        self.degree_2 = QtWidgets.QLabel(self.joint_position)
        self.degree_2.setGeometry(QtCore.QRect(160, 120, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_2.setFont(font)
        self.degree_2.setObjectName("degree_2")

        self.degree_3 = QtWidgets.QLabel(self.joint_position)
        self.degree_3.setGeometry(QtCore.QRect(160, 170, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_3.setFont(font)
        self.degree_3.setObjectName("degree_3")

        self.degree_4 = QtWidgets.QLabel(self.joint_position)
        self.degree_4.setGeometry(QtCore.QRect(160, 215, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_4.setFont(font)
        self.degree_4.setObjectName("degree_4")

        self.degree_5 = QtWidgets.QLabel(self.joint_position)
        self.degree_5.setGeometry(QtCore.QRect(160, 260, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_5.setFont(font)
        self.degree_5.setObjectName("degree_5")

    def retranslate_joint_panel(self, MainWindow, _translate):
        """Apply display strings for this panel's widgets."""
        self.joint_position.setTitle(_translate("MainWindow", "Joint Position"))
        self.degree_0.setText(_translate("MainWindow", "°"))
        self.shoulder.setText(_translate("MainWindow", "S"))
        self.base.setText(_translate("MainWindow", "B"))
        self.elbow.setText(_translate("MainWindow", "E"))
        self.label_elbow.setText(_translate("MainWindow", "Elbow"))
        self.label_shoulder.setText(_translate("MainWindow", "Shoulder"))
        self.label_base.setText(_translate("MainWindow", "Base"))
        self.wrist_1.setText(_translate("MainWindow", "Wrist 1"))
        self.wrist_2.setText(_translate("MainWindow", "Wrist 2"))
        self.wrist_3.setText(_translate("MainWindow", "Wrist 3"))
        self.wrist_4.setText(_translate("MainWindow", "W"))
        self.wrist_5.setText(_translate("MainWindow", "W"))
        self.wrist_6.setText(_translate("MainWindow", "W"))
        self.degree_1.setText(_translate("MainWindow", "°"))
        self.degree_2.setText(_translate("MainWindow", "°"))
        self.degree_3.setText(_translate("MainWindow", "°"))
        self.degree_4.setText(_translate("MainWindow", "°"))
        self.degree_5.setText(_translate("MainWindow", "°"))
