"""DCA1000EVM network configuration panel (IP addresses, ports, capture controls)."""

from PyQt5 import QtCore, QtGui, QtWidgets


class RadarConfigPanel:
    """DCA1000EVM network configuration panel (IP addresses, ports, capture controls).

    Mixin contributing this panel's widgets to :class:`~radar_hgr.ui.layout.main_window.Ui_MainWindow`.
    """

    def build_radar_panel(self, MainWindow):
        """Instantiate and position this panel's widgets."""
        self.RADAR_SYS_CFG = QtWidgets.QGroupBox(self.control_pannel)
        self.RADAR_SYS_CFG.setGeometry(QtCore.QRect(20, 30, 461, 330))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.RADAR_SYS_CFG.setFont(font)
        self.RADAR_SYS_CFG.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.RADAR_SYS_CFG.setObjectName("RADAR_SYS_CFG")

        self.pred = QtWidgets.QCheckBox(self.RADAR_SYS_CFG)
        self.pred.setGeometry(QtCore.QRect(120, 290, 211, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.pred.setFont(font)
        self.pred.setObjectName("pred")

        self.btn_stop_radar = QtWidgets.QPushButton(self.RADAR_SYS_CFG)
        self.btn_stop_radar.setGeometry(QtCore.QRect(270, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_stop_radar.setFont(font)
        self.btn_stop_radar.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.471409, y1:0.102, x2:0.972, y2:0.0965909, stop:0.369318 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_stop_radar.setObjectName("btn_stop_radar")

        self.btn_start_radar = QtWidgets.QPushButton(self.RADAR_SYS_CFG)
        self.btn_start_radar.setGeometry(QtCore.QRect(60, 240, 141, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_start_radar.setFont(font)
        self.btn_start_radar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 253, 255, 255), stop:0.522727 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 253, 255, 255), stop:0.522727 rgba(51, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_start_radar.setObjectName("btn_start_radar")

        self.btn_RESTART_RADAR = QtWidgets.QPushButton(self.RADAR_SYS_CFG)
        self.btn_RESTART_RADAR.setGeometry(QtCore.QRect(340, 140, 101, 51))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_RESTART_RADAR.setFont(font)
        self.btn_RESTART_RADAR.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.489, y1:1, x2:1, y2:1, stop:0 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_RESTART_RADAR.setObjectName("btn_RESTART_RADAR")

        self.label_sysIP_Add = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_sysIP_Add.setGeometry(QtCore.QRect(10, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_sysIP_Add.setFont(font)
        self.label_sysIP_Add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_sysIP_Add.setObjectName("label_sysIP_Add")

        self.frame = QtWidgets.QFrame(self.RADAR_SYS_CFG)
        self.frame.setGeometry(QtCore.QRect(170, 25, 281, 41))
        self.frame.setObjectName("frame")

        self.sys_IP_ADD_0 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_0.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_0.setFont(font)
        self.sys_IP_ADD_0.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_0.setObjectName("sys_IP_ADD_0")

        self.label_0 = QtWidgets.QLabel(self.frame)
        self.label_0.setGeometry(QtCore.QRect(68, 18, 16, 16))
        self.label_0.setObjectName("label_0")

        self.sys_IP_ADD_1 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_1.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_1.setFont(font)
        self.sys_IP_ADD_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_1.setObjectName("sys_IP_ADD_1")

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(138, 18, 16, 16))
        self.label_2.setObjectName("label_2")

        self.sys_IP_ADD_2 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_2.setGeometry(QtCore.QRect(150, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_2.setFont(font)
        self.sys_IP_ADD_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_2.setObjectName("sys_IP_ADD_2")

        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(208, 18, 16, 16))
        self.label_5.setObjectName("label_5")

        self.sys_IP_ADD_3 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_3.setGeometry(QtCore.QRect(220, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_3.setFont(font)
        self.sys_IP_ADD_3.setObjectName("sys_IP_ADD_3")

        self.label_FPGA_IP_ADD = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_FPGA_IP_ADD.setGeometry(QtCore.QRect(10, 65, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_FPGA_IP_ADD.setFont(font)
        self.label_FPGA_IP_ADD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_FPGA_IP_ADD.setObjectName("label_FPGA_IP_ADD")

        self.frame_3 = QtWidgets.QFrame(self.RADAR_SYS_CFG)
        self.frame_3.setGeometry(QtCore.QRect(170, 60, 281, 41))
        self.frame_3.setObjectName("frame_3")

        self.FPGA_IP_ADD_0 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_0.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        self.FPGA_IP_ADD_0.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_0.setFont(font)
        self.FPGA_IP_ADD_0.setObjectName("FPGA_IP_ADD_0")

        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(68, 18, 16, 16))
        self.label_6.setObjectName("label_6")

        self.FPGA_IP_ADD_1 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_1.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_1.setFont(font)
        self.FPGA_IP_ADD_1.setAlignment(QtCore.Qt.AlignCenter)
        self.FPGA_IP_ADD_1.setObjectName("FPGA_IP_ADD_1")

        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(138, 18, 16, 16))
        self.label_7.setObjectName("label_7")

        self.FPGA_IP_ADD_2 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_2.setGeometry(QtCore.QRect(150, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_2.setFont(font)
        self.FPGA_IP_ADD_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FPGA_IP_ADD_2.setObjectName("FPGA_IP_ADD_2")

        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(208, 18, 16, 16))
        self.label_8.setObjectName("label_8")

        self.FPGA_IP_ADD_3 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_3.setGeometry(QtCore.QRect(220, 10, 51, 21))
        self.FPGA_IP_ADD_3.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_3.setFont(font)
        self.FPGA_IP_ADD_3.setObjectName("FPGA_IP_ADD_3")

        self.label_CFG_PORT = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_CFG_PORT.setGeometry(QtCore.QRect(6, 105, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_CFG_PORT.setFont(font)
        self.label_CFG_PORT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_CFG_PORT.setObjectName("label_CFG_PORT")

        self.CFG_PORT = QtWidgets.QSpinBox(self.RADAR_SYS_CFG)
        self.CFG_PORT.setGeometry(QtCore.QRect(180, 105, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.CFG_PORT.setFont(font)
        self.CFG_PORT.setMinimum(1)
        self.CFG_PORT.setMaximum(4096)
        self.CFG_PORT.setAlignment(QtCore.Qt.AlignCenter)
        self.CFG_PORT.setProperty("value", 4096)
        self.CFG_PORT.setDisplayIntegerBase(10)
        self.CFG_PORT.setObjectName("CFG_PORT")

        self.REG_PORT = QtWidgets.QSpinBox(self.RADAR_SYS_CFG)
        self.REG_PORT.setGeometry(QtCore.QRect(180, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.REG_PORT.setFont(font)
        self.REG_PORT.setAlignment(QtCore.Qt.AlignCenter)
        self.REG_PORT.setMinimum(1)
        self.REG_PORT.setMaximum(4098)
        self.REG_PORT.setProperty("value", 4098)
        self.REG_PORT.setDisplayIntegerBase(10)
        self.REG_PORT.setObjectName("REG_PORT")

        self.label_REG_PORT = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_REG_PORT.setGeometry(QtCore.QRect(10, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_REG_PORT.setFont(font)
        self.label_REG_PORT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_REG_PORT.setObjectName("label_REG_PORT")

        self.delay_pkg = QtWidgets.QSpinBox(self.RADAR_SYS_CFG)
        self.delay_pkg.setGeometry(QtCore.QRect(180, 195, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.delay_pkg.setFont(font)
        self.delay_pkg.setAlignment(QtCore.Qt.AlignCenter)
        self.delay_pkg.setMinimum(1)
        self.delay_pkg.setMaximum(4098)
        self.delay_pkg.setProperty("value", 25)
        self.delay_pkg.setDisplayIntegerBase(10)
        self.delay_pkg.setObjectName("delay_pkg")

        self.label_delay_pkg = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_delay_pkg.setGeometry(QtCore.QRect(10, 195, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_delay_pkg.setFont(font)
        self.label_delay_pkg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_delay_pkg.setObjectName("label_delay_pkg")

    def retranslate_radar_panel(self, MainWindow, _translate):
        """Apply display strings for this panel's widgets."""
        self.RADAR_SYS_CFG.setTitle(_translate("MainWindow", "Radar system configuration"))
        self.btn_stop_radar.setText(_translate("MainWindow", "STOP RADAR"))
        self.btn_start_radar.setText(_translate("MainWindow", "START RADAR"))
        self.btn_RESTART_RADAR.setText(_translate("MainWindow", "RESET"))
        self.label_sysIP_Add.setText(_translate("MainWindow", "System IP Address:"))
        self.sys_IP_ADD_0.setText(_translate("MainWindow", "192"))
        self.label_0.setText(_translate("MainWindow", "."))
        self.sys_IP_ADD_1.setText(_translate("MainWindow", "168"))
        self.label_2.setText(_translate("MainWindow", "."))
        self.sys_IP_ADD_2.setText(_translate("MainWindow", "33"))
        self.label_5.setText(_translate("MainWindow", "."))
        self.sys_IP_ADD_3.setText(_translate("MainWindow", "30"))
        self.label_FPGA_IP_ADD.setText(_translate("MainWindow", "FPGA IP Address:"))
        self.FPGA_IP_ADD_0.setText(_translate("MainWindow", "192"))
        self.label_6.setText(_translate("MainWindow", "."))
        self.FPGA_IP_ADD_1.setText(_translate("MainWindow", "168"))
        self.label_7.setText(_translate("MainWindow", "."))
        self.FPGA_IP_ADD_2.setText(_translate("MainWindow", "33"))
        self.label_8.setText(_translate("MainWindow", "."))
        self.FPGA_IP_ADD_3.setText(_translate("MainWindow", "180"))
        self.label_CFG_PORT.setText(_translate("MainWindow", " Config port:"))
        self.label_REG_PORT.setText(_translate("MainWindow", "Record port: "))
        self.label_delay_pkg.setText(_translate("MainWindow", "Packet Delay (µs):"))
        self.pred.setText(_translate("MainWindow", "Predict Hand Gesture ?"))
