"""Tool Center Point (TCP) pose readout group."""

from PyQt5 import QtCore, QtGui, QtWidgets


class TcpReadoutPanel:
    """Tool Center Point (TCP) pose readout group.

    Mixin contributing this panel's widgets to :class:`~radar_hgr.ui.layout.main_window.Ui_MainWindow`.
    """

    def build_tcp_panel(self, MainWindow):
        """Instantiate and position this panel's widgets."""
        self.tool_position = QtWidgets.QGroupBox(self.tab2)
        self.tool_position.setGeometry(QtCore.QRect(1210, 90, 181, 310))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.tool_position.setFont(font)
        self.tool_position.setStyleSheet("background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.522727, radius:0.5, fx:0.507, fy:0.516636, stop:0.244318 rgba(255, 255, 255, 255), stop:0.715909 rgba(255, 255, 255, 255), stop:0.960227 rgba(184, 254, 255, 255));")
        self.tool_position.setObjectName("tool_position")

        self.Unit_X = QtWidgets.QLabel(self.tool_position)
        self.Unit_X.setGeometry(QtCore.QRect(125, 30, 35, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_X.setFont(font)
        self.Unit_X.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_X.setObjectName("Unit_X")

        self.Unit_Y = QtWidgets.QLabel(self.tool_position)
        self.Unit_Y.setGeometry(QtCore.QRect(125, 75, 35, 35))
        font = QtGui.QFont()
        self.Unit_Y.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_Y.setFont(font)
        self.Unit_Y.setObjectName("Unit_Y")

        self.Unit_Z = QtWidgets.QLabel(self.tool_position)
        self.Unit_Z.setGeometry(QtCore.QRect(125, 120, 35, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_Z.setFont(font)
        self.Unit_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_Z.setObjectName("Unit_Z")

        self.Y = QtWidgets.QLabel(self.tool_position)
        self.Y.setGeometry(QtCore.QRect(60, 75, 61, 35))
        self.Y.setAlignment(QtCore.Qt.AlignCenter)
        self.Y.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Y.setFont(font)
        self.Y.setObjectName("Y")

        self.X = QtWidgets.QLabel(self.tool_position)
        self.X.setGeometry(QtCore.QRect(60, 30, 61, 35))
        self.X.setAlignment(QtCore.Qt.AlignCenter)
        self.X.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.X.setFont(font)
        self.X.setObjectName("X")

        self.Z = QtWidgets.QLabel(self.tool_position)
        self.Z.setGeometry(QtCore.QRect(60, 120, 61, 35))
        self.Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Z.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Z.setFont(font)
        self.Z.setObjectName("Z")

        self.label_Z = QtWidgets.QLabel(self.tool_position)
        self.label_Z.setGeometry(QtCore.QRect(30, 120, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_Z.setFont(font)
        self.label_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z.setObjectName("label_Z")

        self.label_Y = QtWidgets.QLabel(self.tool_position)
        self.label_Y.setGeometry(QtCore.QRect(30, 75, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_Y.setFont(font)
        self.label_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y.setObjectName("label_Y")

        self.label_X = QtWidgets.QLabel(self.tool_position)
        self.label_X.setGeometry(QtCore.QRect(30, 30, 16, 35))
        self.label_X.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_X.setFont(font)
        self.label_X.setObjectName("label_X")

        self.label_RZ = QtWidgets.QLabel(self.tool_position)
        self.label_RZ.setGeometry(QtCore.QRect(20, 265, 31, 35))
        self.label_RZ.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_RZ.setFont(font)
        self.label_RZ.setObjectName("label_RZ")

        self.label_RY = QtWidgets.QLabel(self.tool_position)
        self.label_RY.setGeometry(QtCore.QRect(20, 215, 31, 35))
        self.label_RY.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_RY.setFont(font)
        self.label_RY.setObjectName("label_RY")

        self.RX = QtWidgets.QLabel(self.tool_position)
        self.RX.setGeometry(QtCore.QRect(60, 170, 61, 35))
        self.RX.setAlignment(QtCore.Qt.AlignCenter)
        self.RX.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.RX.setFont(font)
        self.RX.setObjectName("RX")

        self.Unit_RX = QtWidgets.QLabel(self.tool_position)
        self.Unit_RX.setGeometry(QtCore.QRect(125, 170, 41, 35))
        font = QtGui.QFont()
        self.Unit_RX.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_RX.setFont(font)
        self.Unit_RX.setObjectName("Unit_RX")

        self.Unit_RY = QtWidgets.QLabel(self.tool_position)
        self.Unit_RY.setGeometry(QtCore.QRect(125, 215, 41, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_RY.setFont(font)
        self.Unit_RY.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_RY.setObjectName("Unit_RY")

        self.RZ = QtWidgets.QLabel(self.tool_position)
        self.RZ.setGeometry(QtCore.QRect(60, 260, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.RZ.setFont(font)
        self.RZ.setAlignment(QtCore.Qt.AlignCenter)
        self.RZ.setStyleSheet("border : 2px solid blue")
        self.RZ.setObjectName("RZ")

        self.label_RX = QtWidgets.QLabel(self.tool_position)
        self.label_RX.setGeometry(QtCore.QRect(20, 170, 31, 35))
        font = QtGui.QFont()
        self.label_RX.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_RX.setFont(font)
        self.label_RX.setObjectName("label_RX")

        self.Unit_RZ = QtWidgets.QLabel(self.tool_position)
        self.Unit_RZ.setGeometry(QtCore.QRect(125, 260, 41, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_RZ.setFont(font)
        self.Unit_RZ.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_RZ.setObjectName("Unit_RZ")

        self.RY = QtWidgets.QLabel(self.tool_position)
        self.RY.setGeometry(QtCore.QRect(60, 215, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.RY.setFont(font)
        self.RY.setAlignment(QtCore.Qt.AlignCenter)
        self.RY.setStyleSheet("border : 2px solid blue")
        self.RY.setObjectName("RY")

    def retranslate_tcp_panel(self, MainWindow, _translate):
        """Apply display strings for this panel's widgets."""
        self.tool_position.setTitle(_translate("MainWindow", "Tool Position"))
        self.Unit_X.setText(_translate("MainWindow", "mm"))
        self.Unit_Y.setText(_translate("MainWindow", "mm"))
        self.Unit_Z.setText(_translate("MainWindow", "mm"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.X.setText(_translate("MainWindow", "X"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.label_Z.setText(_translate("MainWindow", "Z"))
        self.label_Y.setText(_translate("MainWindow", "Y"))
        self.label_X.setText(_translate("MainWindow", "X"))
        self.label_RZ.setText(_translate("MainWindow", "RZ"))
        self.label_RY.setText(_translate("MainWindow", "RY"))
        self.RX.setText(_translate("MainWindow", "RX"))
        self.Unit_RX.setText(_translate("MainWindow", "Rad"))
        self.Unit_RY.setText(_translate("MainWindow", "Rad"))
        self.RZ.setText(_translate("MainWindow", "RZ"))
        self.label_RX.setText(_translate("MainWindow", "RX"))
        self.Unit_RZ.setText(_translate("MainWindow", "Rad"))
        self.RY.setText(_translate("MainWindow", "RY"))
