import os, sys
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
from PyQt5.QtGui import QPixmap, QIcon
from PyQt5.QtCore import Qt
from PyQt5.QtCore import QTimer, QDateTime
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QTextEdit, QScrollArea, QFileDialog, QRadioButton

current_dir = os.path.dirname(os.path.abspath(__file__))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1410, 960)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.A_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.A_tab.setGeometry(QtCore.QRect(0, 0, 1911, 960))
        
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.A_tab.setFont(font)
        self.A_tab.setStyleSheet("background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.522727, radius:0.5, fx:0.507, fy:0.516636, stop:0.244318 rgba(255, 255, 255, 255), stop:0.715909 rgba(255, 255, 255, 255), stop:0.960227 rgba(230, 255, 253, 255));")
        self.A_tab.setObjectName("A_tab")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        
        self.graph = pg.ImageView(self.tab2)
        self.graph.setGeometry(QtCore.QRect(520, 135, 895, 615))
        self.graph.ui.histogram.hide()
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.graph.setFont(font)
        self.graph.setObjectName("graph")
        
        self.control_pannel = QtWidgets.QGroupBox(self.tab2)
        self.control_pannel.setGeometry(QtCore.QRect(10, 100, 501, 820))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.control_pannel.setFont(font)
        self.control_pannel.setStyleSheet("background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.522727, radius:0.5, fx:0.507, fy:0.516636, stop:0.244318 rgba(255, 255, 255, 255), stop:0.715909 rgba(255, 255, 255, 255), stop:0.960227 rgba(184, 254, 255, 255));")
        self.control_pannel.setObjectName("control_pannel")
        
        self.RADAR_SYS_CFG = QtWidgets.QGroupBox(self.control_pannel)
        self.RADAR_SYS_CFG.setGeometry(QtCore.QRect(20, 30, 461, 330))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.RADAR_SYS_CFG.setFont(font)
        self.RADAR_SYS_CFG.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.RADAR_SYS_CFG.setObjectName("RADAR_SYS_CFG")
        
        self.pred = QtWidgets.QCheckBox(self.RADAR_SYS_CFG)
        self.pred.setGeometry(QtCore.QRect(120, 290, 211, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.pred.setFont(font)
        self.pred.setObjectName("pred")        
        
        self.btn_stop_radar = QtWidgets.QPushButton(self.RADAR_SYS_CFG)
        self.btn_stop_radar.setGeometry(QtCore.QRect(270, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_stop_radar.setFont(font)
        self.btn_stop_radar.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.471409, y1:0.102, x2:0.972, y2:0.0965909, stop:0.369318 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_stop_radar.setObjectName("btn_stop_radar")
        
        self.btn_start_radar = QtWidgets.QPushButton(self.RADAR_SYS_CFG)
        self.btn_start_radar.setGeometry(QtCore.QRect(60, 240, 141, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_start_radar.setFont(font)
        self.btn_start_radar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 253, 255, 255), stop:0.522727 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 253, 255, 255), stop:0.522727 rgba(51, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_start_radar.setObjectName("btn_start_radar")
        
        self.btn_RESTART_RADAR = QtWidgets.QPushButton(self.RADAR_SYS_CFG)
        self.btn_RESTART_RADAR.setGeometry(QtCore.QRect(340, 140, 101, 51))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_RESTART_RADAR.setFont(font)
        self.btn_RESTART_RADAR.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.489, y1:1, x2:1, y2:1, stop:0 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_RESTART_RADAR.setObjectName("btn_RESTART_RADAR")
        
        self.label_sysIP_Add = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_sysIP_Add.setGeometry(QtCore.QRect(10, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_sysIP_Add.setFont(font)
        self.label_sysIP_Add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_sysIP_Add.setObjectName("label_sysIP_Add")
        
        self.frame = QtWidgets.QFrame(self.RADAR_SYS_CFG)
        self.frame.setGeometry(QtCore.QRect(170, 25, 281, 41))
        self.frame.setObjectName("frame")
        
        self.sys_IP_ADD_0 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_0.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_0.setFont(font)
        self.sys_IP_ADD_0.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_0.setObjectName("sys_IP_ADD_0")
        
        self.label_0 = QtWidgets.QLabel(self.frame)
        self.label_0.setGeometry(QtCore.QRect(68, 18, 16, 16))
        self.label_0.setObjectName("label_0")
        
        self.sys_IP_ADD_1 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_1.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_1.setFont(font)
        self.sys_IP_ADD_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_1.setObjectName("sys_IP_ADD_1")
        
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(138, 18, 16, 16))
        self.label_2.setObjectName("label_2")
        
        self.sys_IP_ADD_2 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_2.setGeometry(QtCore.QRect(150, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_2.setFont(font)
        self.sys_IP_ADD_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_2.setObjectName("sys_IP_ADD_2")
        
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(208, 18, 16, 16))
        self.label_5.setObjectName("label_5")
        
        self.sys_IP_ADD_3 = QtWidgets.QLineEdit(self.frame)
        self.sys_IP_ADD_3.setGeometry(QtCore.QRect(220, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.sys_IP_ADD_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_IP_ADD_3.setFont(font)
        self.sys_IP_ADD_3.setObjectName("sys_IP_ADD_3")
        
        self.label_FPGA_IP_ADD = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_FPGA_IP_ADD.setGeometry(QtCore.QRect(10, 65, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_FPGA_IP_ADD.setFont(font)
        self.label_FPGA_IP_ADD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_FPGA_IP_ADD.setObjectName("label_FPGA_IP_ADD")
        
        self.frame_3 = QtWidgets.QFrame(self.RADAR_SYS_CFG)
        self.frame_3.setGeometry(QtCore.QRect(170, 60, 281, 41))
        self.frame_3.setObjectName("frame_3")
        
        self.FPGA_IP_ADD_0 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_0.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        self.FPGA_IP_ADD_0.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_0.setFont(font)
        self.FPGA_IP_ADD_0.setObjectName("FPGA_IP_ADD_0")
        
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(68, 18, 16, 16))
        self.label_6.setObjectName("label_6")
        
        self.FPGA_IP_ADD_1 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_1.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_1.setFont(font)
        self.FPGA_IP_ADD_1.setAlignment(QtCore.Qt.AlignCenter)
        self.FPGA_IP_ADD_1.setObjectName("FPGA_IP_ADD_1")
        
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(138, 18, 16, 16))
        self.label_7.setObjectName("label_7")
        
        self.FPGA_IP_ADD_2 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_2.setGeometry(QtCore.QRect(150, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_2.setFont(font)
        self.FPGA_IP_ADD_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FPGA_IP_ADD_2.setObjectName("FPGA_IP_ADD_2")
        
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(208, 18, 16, 16))
        self.label_8.setObjectName("label_8")
        
        self.FPGA_IP_ADD_3 = QtWidgets.QLineEdit(self.frame_3)
        self.FPGA_IP_ADD_3.setGeometry(QtCore.QRect(220, 10, 51, 21))
        self.FPGA_IP_ADD_3.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.FPGA_IP_ADD_3.setFont(font)
        self.FPGA_IP_ADD_3.setObjectName("FPGA_IP_ADD_3")
        
        self.label_CFG_PORT = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_CFG_PORT.setGeometry(QtCore.QRect(6, 105, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_CFG_PORT.setFont(font)
        self.label_CFG_PORT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_CFG_PORT.setObjectName("label_CFG_PORT")
        
        self.CFG_PORT = QtWidgets.QSpinBox(self.RADAR_SYS_CFG)
        self.CFG_PORT.setGeometry(QtCore.QRect(180, 105, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.CFG_PORT.setFont(font)
        self.CFG_PORT.setMinimum(1)
        self.CFG_PORT.setMaximum(4096)
        self.CFG_PORT.setAlignment(QtCore.Qt.AlignCenter)
        self.CFG_PORT.setProperty("value", 4096)
        self.CFG_PORT.setDisplayIntegerBase(10)
        self.CFG_PORT.setObjectName("CFG_PORT")
        
        self.REG_PORT = QtWidgets.QSpinBox(self.RADAR_SYS_CFG)
        self.REG_PORT.setGeometry(QtCore.QRect(180, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.REG_PORT.setFont(font)
        self.REG_PORT.setAlignment(QtCore.Qt.AlignCenter)
        self.REG_PORT.setMinimum(1)
        self.REG_PORT.setMaximum(4098)
        self.REG_PORT.setProperty("value", 4098)
        self.REG_PORT.setDisplayIntegerBase(10)
        self.REG_PORT.setObjectName("REG_PORT")
        
        self.label_REG_PORT = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_REG_PORT.setGeometry(QtCore.QRect(10, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_REG_PORT.setFont(font)
        self.label_REG_PORT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_REG_PORT.setObjectName("label_REG_PORT")
        
        self.delay_pkg = QtWidgets.QSpinBox(self.RADAR_SYS_CFG)
        self.delay_pkg.setGeometry(QtCore.QRect(180, 195, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.delay_pkg.setFont(font)
        self.delay_pkg.setAlignment(QtCore.Qt.AlignCenter)
        self.delay_pkg.setMinimum(1)
        self.delay_pkg.setMaximum(4098)
        self.delay_pkg.setProperty("value", 25)
        self.delay_pkg.setDisplayIntegerBase(10)
        self.delay_pkg.setObjectName("delay_pkg")
        
        self.label_delay_pkg = QtWidgets.QLabel(self.RADAR_SYS_CFG)
        self.label_delay_pkg.setGeometry(QtCore.QRect(10, 195, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_delay_pkg.setFont(font)
        self.label_delay_pkg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_delay_pkg.setObjectName("label_delay_pkg")
        
        self.UR3_SYS_CFG = QtWidgets.QGroupBox(self.control_pannel)
        self.UR3_SYS_CFG.setGeometry(QtCore.QRect(20, 370, 461, 431))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.UR3_SYS_CFG.setFont(font)
        self.UR3_SYS_CFG.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UR3_SYS_CFG.setObjectName("UR3_SYS_CFG")
        
        self.ctrl_ur3 = QtWidgets.QCheckBox(self.UR3_SYS_CFG)
        self.ctrl_ur3.setGeometry(QtCore.QRect(90, 395, 275, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.ctrl_ur3.setFont(font)
        self.ctrl_ur3.setObjectName("ctrl_ur3")
        
        self.btn_stop_UR3 = QtWidgets.QPushButton(self.UR3_SYS_CFG)
        self.btn_stop_UR3.setGeometry(QtCore.QRect(270, 115, 151, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_stop_UR3.setFont(font)
        self.btn_stop_UR3.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.471409, y1:0.102, x2:0.972, y2:0.0965909, stop:0.369318 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_stop_UR3.setObjectName("btn_stop_UR3")
        
        self.btn_start_UR3 = QtWidgets.QPushButton(self.UR3_SYS_CFG)
        self.btn_start_UR3.setGeometry(QtCore.QRect(60, 115, 141, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_start_UR3.setFont(font)
        self.btn_start_UR3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 253, 255, 255), stop:0.522727 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 253, 255, 255), stop:0.522727 rgba(51, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_start_UR3.setObjectName("btn_start_UR3")
        
        self.btn_reset_UR3 = QtWidgets.QPushButton(self.UR3_SYS_CFG)
        self.btn_reset_UR3.setGeometry(QtCore.QRect(320, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        font.setKerning(False)
        self.btn_reset_UR3.setFont(font)
        self.btn_reset_UR3.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.489, y1:1, x2:1, y2:1, stop:0 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_reset_UR3.setObjectName("btn_reset_UR3")
        
        self.label_UR3_IP_ADD = QtWidgets.QLabel(self.UR3_SYS_CFG)
        self.label_UR3_IP_ADD.setGeometry(QtCore.QRect(10, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_UR3_IP_ADD.setFont(font)
        self.label_UR3_IP_ADD.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_UR3_IP_ADD.setObjectName("label_UR3_IP_ADD")
        
        self.frame_4 = QtWidgets.QFrame(self.UR3_SYS_CFG)
        self.frame_4.setGeometry(QtCore.QRect(170, 25, 281, 41))
        self.frame_4.setObjectName("frame_4")
        
        self.UR3_IP_ADD_0 = QtWidgets.QLineEdit(self.frame_4)
        self.UR3_IP_ADD_0.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.UR3_IP_ADD_0.setFont(font)
        self.UR3_IP_ADD_0.setAlignment(QtCore.Qt.AlignCenter)
        self.UR3_IP_ADD_0.setObjectName("UR3_IP_ADD_0")
        
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(68, 18, 16, 16))
        self.label_9.setObjectName("label_9")
        
        self.UR3_IP_ADD_1 = QtWidgets.QLineEdit(self.frame_4)
        self.UR3_IP_ADD_1.setGeometry(QtCore.QRect(80, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.UR3_IP_ADD_1.setFont(font)
        self.UR3_IP_ADD_1.setAlignment(QtCore.Qt.AlignCenter)
        self.UR3_IP_ADD_1.setObjectName("UR3_IP_ADD_1")
        
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(138, 18, 16, 16))
        self.label_10.setObjectName("label_10")
        
        self.UR3_IP_ADD_2 = QtWidgets.QLineEdit(self.frame_4)
        self.UR3_IP_ADD_2.setGeometry(QtCore.QRect(150, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.UR3_IP_ADD_2.setFont(font)
        self.UR3_IP_ADD_2.setAlignment(QtCore.Qt.AlignCenter)
        self.UR3_IP_ADD_2.setObjectName("UR3_IP_ADD_2")
        
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(208, 18, 16, 16))
        self.label_11.setObjectName("label_11")
        
        self.UR3_IP_ADD_3 = QtWidgets.QLineEdit(self.frame_4)
        self.UR3_IP_ADD_3.setGeometry(QtCore.QRect(220, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        self.UR3_IP_ADD_3.setFont(font)
        self.UR3_IP_ADD_3.setAlignment(QtCore.Qt.AlignCenter)
        self.UR3_IP_ADD_3.setObjectName("UR3_IP_ADD_3")
        
        self.label_RTDE_PORT = QtWidgets.QLabel(self.UR3_SYS_CFG)
        self.label_RTDE_PORT.setGeometry(QtCore.QRect(10, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_RTDE_PORT.setFont(font)
        self.label_RTDE_PORT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_RTDE_PORT.setObjectName("label_RTDE_PORT")
        
        self.RTDE_PORT = QtWidgets.QSpinBox(self.UR3_SYS_CFG)
        self.RTDE_PORT.setGeometry(QtCore.QRect(180, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.RTDE_PORT.setFont(font)
        self.RTDE_PORT.setAlignment(QtCore.Qt.AlignCenter)
        self.RTDE_PORT.setMinimum(1)
        self.RTDE_PORT.setMaximum(64000)
        self.RTDE_PORT.setProperty("value", 30004)
        self.RTDE_PORT.setDisplayIntegerBase(10)
        self.RTDE_PORT.setObjectName("RTDE_PORT")
        
        self.frame_5 = QtWidgets.QFrame(self.UR3_SYS_CFG)
        self.frame_5.setGeometry(QtCore.QRect(20, 170, 400, 220))
        self.frame_5.setStyleSheet("background-color: rgb(235, 250, 255);")
        self.frame_5.setObjectName("frame_5")
        
        self.label = QtWidgets.QLabel(self.frame_5)
        pixmap = QPixmap(os.path.join(current_dir, 'xyz.png'))
        resized_pixmap = pixmap.scaled(70, 110)
        self.label.setPixmap(resized_pixmap)
        self.label.setGeometry(0, 10, 70, 110)
        
        self.tools = QtWidgets.QGroupBox(self.frame_5)
        self.tools.setGeometry(QtCore.QRect(5, 125, 100, 90))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.tools.setFont(font)
        self.tools.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tools.setObjectName("tools")
        
        self.option_clamp = QRadioButton("Clamp", self.tools)
        self.option_release = QRadioButton("Release", self.tools)
        vbox = QVBoxLayout()
        vbox.addWidget(self.option_clamp)
        vbox.addWidget(self.option_release)
        self.tools.setLayout(vbox)
    
        self.UP = QtWidgets.QPushButton(self.frame_5)
        self.UP.setGeometry(QtCore.QRect(140, 10, 41, 91))
        self.UP.setIcon(QIcon(os.path.join(current_dir, 'icon/up.png')))
        self.UP.setIconSize(QtCore.QSize(41, 91))
        self.UP.setObjectName("UP")
        
        self.DOWN = QtWidgets.QPushButton(self.frame_5)
        self.DOWN.setGeometry(QtCore.QRect(330, 10, 41, 91))
        self.DOWN.setIcon(QIcon(os.path.join(current_dir, 'icon/down.png')))
        self.DOWN.setIconSize(QtCore.QSize(40, 90))
        self.DOWN.setObjectName("DOWN")
        
        self.IN = QtWidgets.QPushButton(self.frame_5)
        self.IN.setGeometry(QtCore.QRect(210, 60, 91, 51))
        self.IN.setIcon(QIcon(os.path.join(current_dir, 'icon/fw.png')))
        self.IN.setIconSize(QtCore.QSize(90, 50))
        self.IN.setObjectName("IN")
        
        self.LEFT = QtWidgets.QPushButton(self.frame_5)
        self.LEFT.setGeometry(QtCore.QRect(120, 110, 91, 41))
        self.LEFT.setIcon(QIcon(os.path.join(current_dir, 'icon/left.png')))
        self.LEFT.setIconSize(QtCore.QSize(90, 40))
        self.LEFT.setObjectName("LEFT")
        
        self.OUT = QtWidgets.QPushButton(self.frame_5)
        self.OUT.setGeometry(QtCore.QRect(210, 150, 91, 61))
        self.OUT.setIcon(QIcon(os.path.join(current_dir, 'icon/bw.png')))
        self.OUT.setIconSize(QtCore.QSize(91, 61))
        self.OUT.setObjectName("OUT")
        
        self.RIGHT = QtWidgets.QPushButton(self.frame_5)
        self.RIGHT.setGeometry(QtCore.QRect(300, 110, 91, 41))
        self.RIGHT.setIcon(QIcon(os.path.join(current_dir, 'icon/right.png')))
        self.RIGHT.setIconSize(QtCore.QSize(90, 40))
        self.RIGHT.setObjectName("RIGHT")
        
        self.label = QtWidgets.QLabel(self.tab2)
        pixmap = QPixmap(os.path.join(current_dir, 'ICSLAB.png'))
        # pixmap = QPixmap("_internal//ICSLAB.png")
        resized_pixmap = pixmap.scaled(261, 91)
        self.label.setPixmap(resized_pixmap)
        self.label.setGeometry(10, 0, 261, 91)
        
        self.map = QtWidgets.QComboBox(self.tab2)
        self.map.setGeometry(QtCore.QRect(520, 100, 371, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        self.map.setFont(font)
        self.map.setObjectName("map")
        self.map.addItem("")
        self.map.addItem("")
        self.map.addItem("")
        self.map.addItem("")
        self.map.addItem("")
        self.channel = QtWidgets.QComboBox(self.tab2)
        self.channel.setGeometry(QtCore.QRect(890, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        self.channel.setFont(font)
        self.channel.setObjectName("channel")
        self.channel.addItem("")
        self.channel.addItem("")
        self.channel.addItem("")
        self.channel.addItem("")
        self.channel.addItem("")
        
        self.chirp = QtWidgets.QSpinBox(self.tab2)
        self.chirp.setGeometry(QtCore.QRect(1120, 100, 88, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(17)
        font.setBold(False)
        self.chirp.setFont(font)
        self.chirp.setMinimum(1)
        self.chirp.setMaximum(128)
        self.chirp.setObjectName("chirp")
        
        self.gesture = QtWidgets.QLabel(self.tab2)
        self.gesture.setGeometry(QtCore.QRect(520, 20, 871, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(38)
        font.setBold(False)
        self.gesture.setStyleSheet("border : 2px solid blue")
        self.gesture.setAlignment(QtCore.Qt.AlignCenter)
        self.gesture.setFont(font)
        self.gesture.setObjectName("gesture")
        
        self.tool_position = QtWidgets.QGroupBox(self.tab2)
        self.tool_position.setGeometry(QtCore.QRect(1210, 90, 181, 310))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.tool_position.setFont(font)
        self.tool_position.setStyleSheet("background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.522727, radius:0.5, fx:0.507, fy:0.516636, stop:0.244318 rgba(255, 255, 255, 255), stop:0.715909 rgba(255, 255, 255, 255), stop:0.960227 rgba(184, 254, 255, 255));")
        self.tool_position.setObjectName("tool_position")
        
        self.Unit_X = QtWidgets.QLabel(self.tool_position)
        self.Unit_X.setGeometry(QtCore.QRect(125, 30, 35, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_X.setFont(font)
        self.Unit_X.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_X.setObjectName("Unit_X")
        
        self.Unit_Y = QtWidgets.QLabel(self.tool_position)
        self.Unit_Y.setGeometry(QtCore.QRect(125, 75, 35, 35))
        font = QtGui.QFont()
        self.Unit_Y.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_Y.setFont(font)
        self.Unit_Y.setObjectName("Unit_Y")
        
        self.Unit_Z = QtWidgets.QLabel(self.tool_position)
        self.Unit_Z.setGeometry(QtCore.QRect(125, 120, 35, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_Z.setFont(font)
        self.Unit_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_Z.setObjectName("Unit_Z")
        
        self.Y = QtWidgets.QLabel(self.tool_position)
        self.Y.setGeometry(QtCore.QRect(60, 75, 61, 35))
        self.Y.setAlignment(QtCore.Qt.AlignCenter)
        self.Y.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Y.setFont(font)
        self.Y.setObjectName("Y")
        
        self.X = QtWidgets.QLabel(self.tool_position)
        self.X.setGeometry(QtCore.QRect(60, 30, 61, 35))
        self.X.setAlignment(QtCore.Qt.AlignCenter)
        self.X.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.X.setFont(font)
        self.X.setObjectName("X")
        
        self.Z = QtWidgets.QLabel(self.tool_position)
        self.Z.setGeometry(QtCore.QRect(60, 120, 61, 35))
        self.Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Z.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Z.setFont(font)
        self.Z.setObjectName("Z")
        
        self.label_Z = QtWidgets.QLabel(self.tool_position)
        self.label_Z.setGeometry(QtCore.QRect(30, 120, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_Z.setFont(font)
        self.label_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z.setObjectName("label_Z")
        
        self.label_Y = QtWidgets.QLabel(self.tool_position)
        self.label_Y.setGeometry(QtCore.QRect(30, 75, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_Y.setFont(font)
        self.label_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y.setObjectName("label_Y")
        
        self.label_X = QtWidgets.QLabel(self.tool_position)
        self.label_X.setGeometry(QtCore.QRect(30, 30, 16, 35))
        self.label_X.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_X.setFont(font)
        self.label_X.setObjectName("label_X")
        
        self.label_RZ = QtWidgets.QLabel(self.tool_position)
        self.label_RZ.setGeometry(QtCore.QRect(20, 265, 31, 35))
        self.label_RZ.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_RZ.setFont(font)
        self.label_RZ.setObjectName("label_RZ")
        
        self.label_RY = QtWidgets.QLabel(self.tool_position)
        self.label_RY.setGeometry(QtCore.QRect(20, 215, 31, 35))
        self.label_RY.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_RY.setFont(font)
        self.label_RY.setObjectName("label_RY")
        
        self.RX = QtWidgets.QLabel(self.tool_position)
        self.RX.setGeometry(QtCore.QRect(60, 170, 61, 35))
        self.RX.setAlignment(QtCore.Qt.AlignCenter)
        self.RX.setStyleSheet("border : 2px solid blue")
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.RX.setFont(font)
        self.RX.setObjectName("RX")
        
        self.Unit_RX = QtWidgets.QLabel(self.tool_position)
        self.Unit_RX.setGeometry(QtCore.QRect(125, 170, 41, 35))
        font = QtGui.QFont()
        self.Unit_RX.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_RX.setFont(font)
        self.Unit_RX.setObjectName("Unit_RX")
        
        self.Unit_RY = QtWidgets.QLabel(self.tool_position)
        self.Unit_RY.setGeometry(QtCore.QRect(125, 215, 41, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_RY.setFont(font)
        self.Unit_RY.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_RY.setObjectName("Unit_RY")
        
        self.RZ = QtWidgets.QLabel(self.tool_position)
        self.RZ.setGeometry(QtCore.QRect(60, 260, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.RZ.setFont(font)
        self.RZ.setAlignment(QtCore.Qt.AlignCenter)
        self.RZ.setStyleSheet("border : 2px solid blue")
        self.RZ.setObjectName("RZ")
        
        self.label_RX = QtWidgets.QLabel(self.tool_position)
        self.label_RX.setGeometry(QtCore.QRect(20, 170, 31, 35))
        font = QtGui.QFont()
        self.label_RX.setAlignment(QtCore.Qt.AlignCenter)
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_RX.setFont(font)
        self.label_RX.setObjectName("label_RX")
        
        self.Unit_RZ = QtWidgets.QLabel(self.tool_position)
        self.Unit_RZ.setGeometry(QtCore.QRect(125, 260, 41, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.Unit_RZ.setFont(font)
        self.Unit_RZ.setAlignment(QtCore.Qt.AlignCenter)
        self.Unit_RZ.setObjectName("Unit_RZ")
        
        self.RY = QtWidgets.QLabel(self.tool_position)
        self.RY.setGeometry(QtCore.QRect(60, 215, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.RY.setFont(font)
        self.RY.setAlignment(QtCore.Qt.AlignCenter)
        self.RY.setStyleSheet("border : 2px solid blue")
        self.RY.setObjectName("RY")
        
        self.label_chirp = QtWidgets.QLabel(self.tab2)
        self.label_chirp.setGeometry(QtCore.QRect(1070, 100, 51, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_chirp.setFont(font)
        self.label_chirp.setObjectName("label_chirp")
        
        self.scroll_area = QScrollArea(self.tab2)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setHorizontalScrollBarPolicy(1)
        self.output_widget = QWidget()
        self.layout = QVBoxLayout()
        self.output_widget.setLayout(self.layout)
        self.text_edit = QTextEdit()
        self.text_edit.setReadOnly(True)
        self.layout.addWidget(self.text_edit)
        self.scroll_area.setWidget(self.output_widget)
        self.scroll_area.setGeometry(QtCore.QRect(1395, 20, 480, 960))
        self.scroll_area.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scroll_area.setObjectName("logs")
        
        self.btn_a = QtWidgets.QPushButton(self.tab2)
        self.btn_a.setGeometry(QtCore.QRect(520, 780, 101, 101))
        self.btn_a.setIcon(QIcon(os.path.join(current_dir, 'logs.jpg')))
        self.btn_a.setIconSize(QtCore.QSize(100, 100))
        self.btn_a.setObjectName("btn_a")
        
        self.btn_file = QtWidgets.QPushButton(self.tab2)
        self.btn_file.setGeometry(QtCore.QRect(650, 780, 50, 50))
        self.btn_file.setIcon(QIcon(os.path.join(current_dir, 'file_brower.png')))
        self.btn_file.setIconSize(QtCore.QSize(51, 51))
        self.btn_file.setObjectName("btn_file")
        
        self.path_model = QtWidgets.QLabel(self.tab2)
        self.path_model.setGeometry(QtCore.QRect(700, 780, 510, 100))
        self.path_model.setWordWrap(True)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.path_model.setFont(font)
        self.path_model.setAlignment(QtCore.Qt.AlignCenter)
        self.path_model.setStyleSheet("border : 1px solid black")
        self.path_model.setObjectName("path_model")
        
        self.label_gesture = QtWidgets.QLabel(self.tab2)
        self.label_gesture.setGeometry(QtCore.QRect(280, 20, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(False)
        self.label_gesture.setFont(font)
        self.label_gesture.setObjectName("label_gesture")
        
        self.joint_position = QtWidgets.QGroupBox(self.tab2)
        self.joint_position.setGeometry(QtCore.QRect(1210, 405, 181, 310))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        self.joint_position.setFont(font)
        self.joint_position.setStyleSheet("background-color: qradialgradient(spread:reflect, cx:0.5, cy:0.522727, radius:0.5, fx:0.507, fy:0.516636, stop:0.244318 rgba(255, 255, 255, 255), stop:0.715909 rgba(255, 255, 255, 255), stop:0.960227 rgba(184, 254, 255, 255));")
        self.joint_position.setObjectName("joint_position")
        
        self.degree_0 = QtWidgets.QLabel(self.joint_position)
        self.degree_0.setGeometry(QtCore.QRect(160, 30, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_0.setFont(font)
        self.degree_0.setObjectName("degree_0")
        
        self.shoulder = QtWidgets.QLabel(self.joint_position)
        self.shoulder.setGeometry(QtCore.QRect(90, 75, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.shoulder.setFont(font)
        self.shoulder.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulder.setStyleSheet("border : 2px solid blue")
        self.shoulder.setObjectName("shoulder")
        
        self.base = QtWidgets.QLabel(self.joint_position)
        self.base.setGeometry(QtCore.QRect(90, 30, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.base.setFont(font)
        self.base.setAlignment(QtCore.Qt.AlignCenter)
        self.base.setStyleSheet("border : 2px solid blue")
        self.base.setObjectName("base")
        
        self.elbow = QtWidgets.QLabel(self.joint_position)
        self.elbow.setGeometry(QtCore.QRect(90, 120, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.elbow.setFont(font)
        self.elbow.setAlignment(QtCore.Qt.AlignCenter)
        self.elbow.setStyleSheet("border : 2px solid blue")
        self.elbow.setObjectName("elbow")
        
        self.label_elbow = QtWidgets.QLabel(self.joint_position)
        self.label_elbow.setGeometry(QtCore.QRect(10, 120, 51, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_elbow.setFont(font)
        self.label_elbow.setObjectName("label_elbow")
        
        self.label_shoulder = QtWidgets.QLabel(self.joint_position)
        self.label_shoulder.setGeometry(QtCore.QRect(10, 75, 75, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_shoulder.setFont(font)
        self.label_shoulder.setObjectName("label_shoulder")
        
        self.label_base = QtWidgets.QLabel(self.joint_position)
        self.label_base.setGeometry(QtCore.QRect(10, 30, 41, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.label_base.setFont(font)
        self.label_base.setObjectName("label_base")
        
        self.wrist_1 = QtWidgets.QLabel(self.joint_position)
        self.wrist_1.setGeometry(QtCore.QRect(10, 170, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_1.setFont(font)
        self.wrist_1.setObjectName("wrist_1")
        
        self.wrist_2 = QtWidgets.QLabel(self.joint_position)
        self.wrist_2.setGeometry(QtCore.QRect(10, 215, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_2.setFont(font)
        self.wrist_2.setObjectName("wrist_2")
        
        self.wrist_3 = QtWidgets.QLabel(self.joint_position)
        self.wrist_3.setGeometry(QtCore.QRect(10, 260, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_3.setFont(font)
        self.wrist_3.setObjectName("wrist_3")
        
        self.wrist_4 = QtWidgets.QLabel(self.joint_position)
        self.wrist_4.setGeometry(QtCore.QRect(90, 170, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_4.setFont(font)
        self.wrist_4.setAlignment(QtCore.Qt.AlignCenter)
        self.wrist_4.setStyleSheet("border : 2px solid blue")
        self.wrist_4.setObjectName("wrist_4")
        
        self.wrist_5 = QtWidgets.QLabel(self.joint_position)
        self.wrist_5.setGeometry(QtCore.QRect(90, 215, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_5.setFont(font)
        self.wrist_5.setAlignment(QtCore.Qt.AlignCenter)
        self.wrist_5.setStyleSheet("border : 2px solid blue")
        self.wrist_5.setObjectName("wrist_5")
        
        self.wrist_6 = QtWidgets.QLabel(self.joint_position)
        self.wrist_6.setGeometry(QtCore.QRect(90, 260, 61, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.wrist_6.setFont(font)
        self.wrist_6.setAlignment(QtCore.Qt.AlignCenter)
        self.wrist_6.setStyleSheet("border : 2px solid blue")
        self.wrist_6.setObjectName("wrist_6")
        
        self.degree_1 = QtWidgets.QLabel(self.joint_position)
        self.degree_1.setGeometry(QtCore.QRect(160, 75, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_1.setFont(font)
        self.degree_1.setObjectName("degree_1")
        
        self.degree_2 = QtWidgets.QLabel(self.joint_position)
        self.degree_2.setGeometry(QtCore.QRect(160, 120, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_2.setFont(font)
        self.degree_2.setObjectName("degree_2")
        
        self.degree_3 = QtWidgets.QLabel(self.joint_position)
        self.degree_3.setGeometry(QtCore.QRect(160, 170, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_3.setFont(font)
        self.degree_3.setObjectName("degree_3")
        
        self.degree_4 = QtWidgets.QLabel(self.joint_position)
        self.degree_4.setGeometry(QtCore.QRect(160, 215, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_4.setFont(font)
        self.degree_4.setObjectName("degree_4")
        
        self.degree_5 = QtWidgets.QLabel(self.joint_position)
        self.degree_5.setGeometry(QtCore.QRect(160, 260, 16, 35))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(16)
        font.setBold(False)
        self.degree_5.setFont(font)
        self.degree_5.setObjectName("degree_5")
        
        self.btn_EXIT = QtWidgets.QPushButton(self.tab2)
        self.btn_EXIT.setGeometry(QtCore.QRect(1260, 780, 101, 101))
        self.btn_EXIT.setIcon(QIcon(os.path.join(current_dir, 'icon/quit.png')))
        self.btn_EXIT.setIconSize(QtCore.QSize(100, 100))
        self.btn_EXIT.setObjectName("btn_EXIT")
        self.btn_EXIT.clicked.connect(MainWindow.close) 
        
        self.A_tab.addTab(self.tab2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.A_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DEMO"))
        MainWindow.setWindowIcon(QIcon(os.path.join(current_dir, 'icon/ICSLAB.ico')))
        
        self.control_pannel.setTitle(_translate("MainWindow", "Control Pannel"))
        self.RADAR_SYS_CFG.setTitle(_translate("MainWindow", "Radar system configuration"))
        self.btn_stop_radar.setText(_translate("MainWindow", "STOP RADAR"))
        self.btn_start_radar.setText(_translate("MainWindow", "START RADAR"))
        self.btn_RESTART_RADAR.setText(_translate("MainWindow", "RESET"))
        self.label_sysIP_Add.setText(_translate("MainWindow", "System IP Address:"))
        self.sys_IP_ADD_0.setText(_translate("MainWindow", "192"))
        self.label_0.setText(_translate("MainWindow", "."))
        self.sys_IP_ADD_1.setText(_translate("MainWindow", "168"))
        self.path_model.setText(_translate("MainWindow", "MODEL PATH"))
        self.label_2.setText(_translate("MainWindow", "."))
        self.sys_IP_ADD_2.setText(_translate("MainWindow", "33"))
        self.label_5.setText(_translate("MainWindow", "."))
        self.sys_IP_ADD_3.setText(_translate("MainWindow", "30"))
        self.label_FPGA_IP_ADD.setText(_translate("MainWindow", "FPGA IP Address:"))
        self.FPGA_IP_ADD_0.setText(_translate("MainWindow", "192"))
        self.label_6.setText(_translate("MainWindow", "."))
        self.FPGA_IP_ADD_1.setText(_translate("MainWindow", "168"))
        self.label_7.setText(_translate("MainWindow", "."))
        self.FPGA_IP_ADD_2.setText(_translate("MainWindow", "33"))
        self.label_8.setText(_translate("MainWindow", "."))
        self.FPGA_IP_ADD_3.setText(_translate("MainWindow", "180"))
        self.label_CFG_PORT.setText(_translate("MainWindow", " Config port:"))
        self.label_REG_PORT.setText(_translate("MainWindow", "Record port: "))
        self.label_delay_pkg.setText(_translate("MainWindow", "Packet Delay (µs):"))
        self.UR3_SYS_CFG.setTitle(_translate("MainWindow", "UR3 system configuration"))
        self.tools.setTitle(_translate("MainWindow", "Tools"))
        self.btn_stop_UR3.setText(_translate("MainWindow", "STOP UR3"))
        self.btn_start_UR3.setText(_translate("MainWindow", "START UR3"))
        self.btn_reset_UR3.setText(_translate("MainWindow", "RESET"))
        self.label_UR3_IP_ADD.setText(_translate("MainWindow", "UR3 IP Address:"))
        self.UR3_IP_ADD_0.setText(_translate("MainWindow", "169"))
        self.label_9.setText(_translate("MainWindow", "."))
        self.UR3_IP_ADD_1.setText(_translate("MainWindow", "254"))
        self.label_10.setText(_translate("MainWindow", "."))
        self.UR3_IP_ADD_2.setText(_translate("MainWindow", "200"))
        self.label_11.setText(_translate("MainWindow", "."))
        self.UR3_IP_ADD_3.setText(_translate("MainWindow", "239"))
        self.label_RTDE_PORT.setText(_translate("MainWindow", "RTDE port:"))
        self.ctrl_ur3.setText(_translate("MainWindow", "Control UR3 by Hand Gesture?"))
        self.pred.setText(_translate("MainWindow", "Predict Hand Gesture ?"))
        self.map.setItemText(0, _translate("MainWindow", "Map"))
        self.map.setItemText(1, _translate("MainWindow", "Raw data"))
        self.map.setItemText(2, _translate("MainWindow", "Range - FFT"))
        self.map.setItemText(3, _translate("MainWindow", "Range - Doppler Map"))
        self.map.setItemText(4, _translate("MainWindow", "micro - Doppler Map"))
        self.channel.setItemText(0, _translate("MainWindow", "Channel"))
        self.channel.setItemText(1, _translate("MainWindow", "RX1"))
        self.channel.setItemText(2, _translate("MainWindow", "RX2"))
        self.channel.setItemText(3, _translate("MainWindow", "RX3"))
        self.channel.setItemText(4, _translate("MainWindow", "RX4"))
        self.gesture.setText(_translate("MainWindow", "Unknown"))
        self.tool_position.setTitle(_translate("MainWindow", "Tool Position"))
        self.Unit_X.setText(_translate("MainWindow", "mm"))
        self.Unit_Y.setText(_translate("MainWindow", "mm"))
        self.Unit_Z.setText(_translate("MainWindow", "mm"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.X.setText(_translate("MainWindow", "X"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.label_Z.setText(_translate("MainWindow", "Z"))
        self.label_Y.setText(_translate("MainWindow", "Y"))
        self.label_X.setText(_translate("MainWindow", "X"))
        self.label_RZ.setText(_translate("MainWindow", "RZ"))
        self.label_RY.setText(_translate("MainWindow", "RY"))
        self.RX.setText(_translate("MainWindow", "RX"))
        self.Unit_RX.setText(_translate("MainWindow", "Rad"))
        self.Unit_RY.setText(_translate("MainWindow", "Rad"))
        self.RZ.setText(_translate("MainWindow", "RZ"))
        self.label_RX.setText(_translate("MainWindow", "RX"))
        self.Unit_RZ.setText(_translate("MainWindow", "Rad"))
        self.RY.setText(_translate("MainWindow", "RY"))
        self.label_chirp.setText(_translate("MainWindow", "Chirp:"))
        self.label_gesture.setText(_translate("MainWindow", "Gesture:"))
        self.joint_position.setTitle(_translate("MainWindow", "Joint Position"))
        self.degree_0.setText(_translate("MainWindow", "°"))
        self.shoulder.setText(_translate("MainWindow", "S"))
        self.base.setText(_translate("MainWindow", "B"))
        self.elbow.setText(_translate("MainWindow", "E"))
        self.label_elbow.setText(_translate("MainWindow", "Elbow"))
        self.label_shoulder.setText(_translate("MainWindow", "Shoulder"))
        self.label_base.setText(_translate("MainWindow", "Base"))
        self.wrist_1.setText(_translate("MainWindow", "Wrist 1"))
        self.wrist_2.setText(_translate("MainWindow", "Wrist 2"))
        self.wrist_3.setText(_translate("MainWindow", "Wrist 3"))
        self.wrist_4.setText(_translate("MainWindow", "W"))
        self.wrist_5.setText(_translate("MainWindow", "W"))
        self.wrist_6.setText(_translate("MainWindow", "W"))
        self.degree_1.setText(_translate("MainWindow", "°"))
        self.degree_2.setText(_translate("MainWindow", "°"))
        self.degree_3.setText(_translate("MainWindow", "°"))
        self.degree_4.setText(_translate("MainWindow", "°"))
        self.degree_5.setText(_translate("MainWindow", "°"))
        self.A_tab.setTabText(self.A_tab.indexOf(self.tab2), _translate("MainWindow", "DEMO"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
